# Generated by Django 5.1.1 on 2025-02-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projet_User',
        ),
    ]
