# Generated by Django 5.1.1 on 2025-01-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
