# Generated by Django 5.1.1 on 2025-02-18 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_1', '0002_alter_projet_user_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet_user',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='projet_user',
            constraint=models.UniqueConstraint(fields=('name', 'utilisateur'), name='unique_name_per_user'),
        ),
    ]
